### PR TITLE
support windows gnu and msvc targets

### PR DESCRIPTION
**Pull request by macalimlim**
support both 32 and 64 bit windows-gnu targets

### CODE REVIEW

**Comment by macalimlim** [comment]
should resolve #7

**Review by toasteater — COMMENTED** [review]
Shouldn't this add the `msvc` targets currently used in #36? The `gnu` targets are commented out in that one.

**Comment by macalimlim** [comment]
Im planning to support both `msvc` and `gnu` targets, which `msvc` will be the default. Users can just comment and uncomment between the two. Im waiting for the developments in  another [PR](https://github.com/godot-rust/godot-rust-template/pull/33) which adds support for `msvc`

**Comment by macalimlim** [comment]
this should now support both gnu and msvc

**Review by toasteater — APPROVED** [review]
Looks good to me!

**Comment by macalimlim** [comment]
Thanks :+1:

**Pull request merged**
