### PR TITLE
support ios target

### LINKED ISSUE #6: support iOS targets
The template should have support for iOS targets from building the library to exporting the game

### PR DESCRIPTION
**Pull request by macalimlim**
should resolve #6

### CODE REVIEW

**Comment by macalimlim** [comment]
@toasteater and @karroffel please review...

**Comment by macalimlim** [comment]
@toasteater and @karroffel I got stuck at this error. Any idea why this is happening? 

rust-ios-gdnative-bindings-error

**Comment by toasteater** [comment]
@macalimlim It seems like the script is trying to build from the *MacOSX* SDK, not the iOS one. I'm not sure why this is happening: the makefile changes in this PR seem fine.

**Comment by toasteater** [comment]
The include paths should be determined here according to the target triple: https://github.com/godot-rust/godot-rust/blob/9dd92ea0b6db6ff403e259cd95206c20e195d395/gdnative-sys/build.rs#L23

What is the output of `xcrun --sdk iphoneos --show-sdk-path`?

**Comment by macalimlim** [comment]
> What is the output of `xcrun --sdk iphoneos --show-sdk-path`?
Oh it says the `iphoneos SDK not found`. Seems like I have to install Xcode for this. 
then run this command before the build `xcode-select --switch /Applications/Xcode.app`

**Comment by toasteater** [comment]
That should explain it. Perhaps clang falled back to the system headers since it cannot find iOS ones.

**Comment by macalimlim** [comment]
Uhhhm is there a way to install the needed sdk without installing the Xcode IDE?

**Comment by toasteater** [comment]
Googling didn't yield anything recent.

**Comment by macalimlim** [comment]
yeah, so I guess the changes in the PR is enough? as long users have followed the steps [here](https://github.com/godot-rust/godot-rust-template/wiki#on-macos-x) for setting up the dev environment...

**Review by toasteater — APPROVED** [review]
Yes, this should be enough.

**Pull request merged**
