### PR TITLE
exclude LICENSE from generated project directory 

### PR DESCRIPTION
**Pull request by macalimlim**
make year dynamic by getting current year

### CODE REVIEW

**Review by toasteater — COMMENTED** [review]
I'm a bit confused. Is the `LICENSE` file supposed to be the license for *this template*, or the license for the generated crates? Because I don't think most users would want a MIT license in their games by default. I think we should make it clear that `LICENSE` is the license for this template, and [exclude it from the template](https://github.com/ashleygwilliams/cargo-generate#include--exclude)?

**Comment by macalimlim** [comment]
Yes I can exclude the `LICENSE` from the generated directory and place the `LICENSE` details (that is used by the template) into the [wiki](https://github.com/godot-rust/godot-rust-template/wiki)

**Comment by toasteater** [comment]
If you do so, maybe `LICENSE` should just say `Copyright (c) 2020 The godot-rust developers`?

**Comment by macalimlim** [comment]
Sure :+1:

**Review by toasteater — APPROVED** [review]
Maybe the commit message can be changed too, but the changes look good to me!

**Pull request merged**
